const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with:", deployer.address);
  console.log("Balance:", hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address)), "ETH\n");

  // Deploy NFTCollection
  const NFTCollection = await hre.ethers.getContractFactory("NFTCollection");
  const nftCollection = await NFTCollection.deploy("AuraVerse", "AURA", 250);
  await nftCollection.waitForDeployment();
  const nftAddr = await nftCollection.getAddress();
  console.log("✅ NFTCollection deployed to:", nftAddr);

  // Deploy NFTMarketplace (2.5% fee)
  const NFTMarketplace = await hre.ethers.getContractFactory("NFTMarketplace");
  const marketplace = await NFTMarketplace.deploy(250);
  await marketplace.waitForDeployment();
  const mpAddr = await marketplace.getAddress();
  console.log("✅ NFTMarketplace deployed to:", mpAddr);

  // Deploy NFTAuction (2.5% fee)
  const NFTAuction = await hre.ethers.getContractFactory("NFTAuction");
  const auction = await NFTAuction.deploy(250);
  await auction.waitForDeployment();
  const aucAddr = await auction.getAddress();
  console.log("✅ NFTAuction deployed to:", aucAddr);

  // ─── Auto-update frontend constants.js with deployed addresses ────────────
  const constantsPath = path.join(__dirname, "..", "frontend", "src", "utils", "constants.js");
  const network = await hre.ethers.provider.getNetwork();
  const chainId = Number(network.chainId);

  const constantsContent = `// Auto-generated by deploy script — ${new Date().toISOString()}
// Network: ${network.name} (chainId: ${chainId})

export const NFT_COLLECTION_ADDRESS = "${nftAddr}";
export const MARKETPLACE_ADDRESS = "${mpAddr}";
export const AUCTION_ADDRESS = "${aucAddr}";

export const SUPPORTED_CHAIN_ID = ${chainId === 31337 ? 11155111 : chainId}; // Sepolia

export const DEMO_NFTS = [];
`;

  fs.writeFileSync(constantsPath, constantsContent);
  console.log("\n📝 Updated frontend/src/utils/constants.js with deployed addresses");
  console.log("\n🎉 All contracts deployed successfully!");
  console.log("─────────────────────────────────────────");
  console.log("NFTCollection:  ", nftAddr);
  console.log("NFTMarketplace: ", mpAddr);
  console.log("NFTAuction:     ", aucAddr);
  console.log("─────────────────────────────────────────");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});